development:
  adapter: postgresql
  encoding: unicode
  database: keeva_development
  pool: 5
<<<<<<< HEAD
  username: hildenton
=======
  username: timproctor
>>>>>>> 6a3ee2a4d438a91588d4bd5c0c367f2e97ff2e11
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: keeva_test
  pool: 5
<<<<<<< HEAD
  username: hildenton
=======
  username: timproctor
>>>>>>> 6a3ee2a4d438a91588d4bd5c0c367f2e97ff2e11
  password:
