development:
  adapter: postgresql
  encoding: unicode
  database: keeva_development
  pool: 5
  username: hildenton
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: keeva_test
  pool: 5
  username: hildenton
  password:
