development:
  adapter: postgresql
  encoding: unicode
  database: keeva_development
  pool: 5
  username: andy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: keeva_test
  pool: 5
  username: andy
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: keeva_production
  pool: 5
  username: andy
  password:
