@loans = [  [ title: "Buy pigs for breeding and then selling",
   amount: 77500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "October 15, 2014",
   repayments_begin: "November 4, 2014",
   monthly_payment: 5500,
   category_ids: ["1", "2","3"]
   ],

   [ title: "Buy Fertilizers",
     amount: 47500,
     description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
     requested_by: "December 6, 2014",
     repayments_begin: "February 4, 2015",
     monthly_payment: 8000,
     category_ids: ["1", "2", "3", "4"]
   ],

  [ title: "Buy Fertilizers and seeds",
   amount: 125000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 5000,
   category_ids: ["1"]
   ],

  [ title: "Buy young cattle",
   amount: 202500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "October 7, 2014",
   repayments_begin: "March 4, 2015",
   monthly_payment: 15000,
   category_ids: ["1", "4"]
 ],

  [ title: "Frais de labour, achat d’intrants",
   amount: 100000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "March 4, 2015",
   repayments_begin: "August 7, 2015",
   monthly_payment: 10000,
   category_ids: ["1"]
 ],

  [ title: "Purchase sacks of corn",
   amount: 15000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 1150,
   category_ids: ["2"]
],

  [ title: "Buy boats, trophies, and baseballs to sell",
   amount: 77500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 4550,
   category_ids: ["2"]
],

  [ title: "Repair dangerous home staircase",
   amount: 117500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 6000,
   category_ids: ["2", "4"]
],
  [ title: "Buy the latest video games",
   amount: 50000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 3500,
   category_ids: ["2", "3"]
],
  [ title: "Purchase goods to stock and open a market",
   amount: 300000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 15000,
   category_ids: ["2"]
],
  [ title: "Pay a member's school fees",
   amount: 552500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 69000,
   category_ids: ["3"]
],
  [ title: "Pay semester school fees",
   amount: 72600,
   description:"Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 4000,
   category_ids: ["3","2"]
],
  [ title: "Cover higher education expenses",
   amount: 732500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 7250,
   category_ids: ["3"]
],
  [ title: "Buy butifarras-making supplies",
   amount: 75000,
   description:"Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 5000,
   category_ids: ["4","6","5"]
],
  [ title: "Buy chickens and vaccines",
   amount: 50000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 6250,
   category_ids: ["4","5","6"]
],
  [ title: "Buy miscellaneous goods for resale",
   amount: 102500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 11400,
   category_ids: ["5", "6","4","3","1"]
],
  [ title: "Buy beauty salon supplies",
   amount: 800000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 40000,
   category_ids: ["5", "6","4"]
],
  [ title: "Build a small biogas digester",
   amount: 100000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 3700,
   category_ids: ["5", "6","3"]
],
  [ title: "Paint his residence",
   amount: 20000,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 2200,
   category_ids: ["6", "5","1"]
],
  [ title: "Buy cement, sand, and other materials for house repair.",
   amount: 37500,
   description: "Freddy Francisco Senior is married with four children, with just one of them of the age to be under their responsibility. He originates from one of the northern municipalities of Chinandega, located in the west of the country, an area that is characterized by being productively commercial and a mining town with livestock. He is a micro-entrepreneur and is a manager of his own business which butchers pigs and sells them. This business is located in his house and from very early he has sold products to nearby regions where he has permanent and temporary cash customers.",
   requested_by: "December 6, 2014",
   repayments_begin: "February 4, 2015",
   monthly_payment: 900,
   category_ids: ["6", "5","1"]
]
]
